image: mkemp/cypress-jdk-maven-atlassian-sdk:cypress6.2.0-node12.18.3-chrome87-ff82
pipelines:
    default:
        - parallel:
              - step:
                    caches:
                        - node
                        - maven
                    name: E2E tests
                    size: 2x
                    script:
                        - npm ci
                        - npm run test:ci
                    artifacts:
                        - screenshots/*.png
